version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    image: php:8.0-apache
    volumes:
      - ./php/wordpress/:/var/www/html/
    ports:
      - 8000:80
    links:
      - postgres


  drupal:
    image: drupal:latest
    ports:
      - 90:90
      - 8181:80
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites
    restart: always
    links:
      - postgres

  postgres:
    image: postgres:10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST: joe_task_postgres_1
      POSTGRES_PASSWORD: 12345678
    volumes:
        - db_data:/var/lib/postgresql/data
    restart: always
volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:
  db_data:
